### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by webdevbrian** [cloudwalking/Hermes#1]
Nevermind

**Comment by cloudwalking** [comment]
The FLORA (Arduino) that I use has an onboard voltage regulator, it can take anywhere from 3-9V without problem. So technically yes the battery is regulated but not by any additional work (circuitry) by me.

The 5V LED strip is powered by the same LiPo battery as the Arduino. Both types of LED I have used (LPD8806 and WS2812) perform fine at 3V.

**Comment by webdevbrian** [comment]
Hmm ... wired and soldered on of these up to what was displayed, uploaded your sketch and absolutely nothing. Weird.

Build another one, same thing, no juice.

I'm wondering if there is an issue running a 5v LED strip @ 3.7V .... ? Totally at a loss, I can't even get either of my floras to print anything via serial, really really confused here ...?

**Comment by NicoHood** [comment]
Depends on the chip that is used for the strip. See the datasheet for voltage rates. The guys at fastled might be able to help you:
https://gitter.im/FastLED/public
https://github.com/FastLED/FastLED

**Comment by webdevbrian** [comment]
I got this one - http://www.adafruit.com/product/306

**Comment by webdevbrian** [comment]
I literally bought everything this guy listed -- the fact that I'm not even getting anything via serial with his code is ... weird. It uploads, no errors, absolutely nothing via serial nothing else beyond that either :(
