### ISSUE TITLE
Parts list correct?

### ISSUE THREAD

**Issue by webdevbrian** [cloudwalking/Hermes#2]
Hi,

Just built two of these -- wondering if the parts list is correct, via your list I got my LEDs from ADAFruit (much like the other things you listed) all which I bought from ada fruit.

No power to the LEDs, but I did verify that the accelerometer is working (via the snippet in the codebase that logs it to serial) for some reason my accelerometer indicated a calibration of '1052' -- Im' guessing that's magnitude? no idea.

Any how, even in your wiring diagram, you can see that the strip that you used is a 5V strip. I'm wondering if this makes sense because the lipo battery is 3.7 ... a bit odd.

Again, I uploaded the code fine, no errors, followed the wiring schematic perfectly, and have no lights at all -- quite odd.

Any help would be appreciated -- thanks!

**Comment by webdevbrian** [comment]
Switched the ada_fruit neo pixel library with the LPD8806 library within the code ... same thing, absolutely nothing happens ...

**Comment by webdevbrian** [comment]
Also included the SPI library (needed with the LPD8806 lib) -- no beans

**Comment by NicoHood** [comment]
Try FastLed as suggested. Try a blink example. Then go on with testing.

**Comment by webdevbrian** [comment]
Nothing, not even the blink example works ... which is why I'm questioning if the LED strip can even function like this (maybe he incorrectly listed the LED strip?) I have no idea...

Triple checked my wiring on both floras, and it's perfect. I get absolutely no LEDs -- code compiles and uploads, like I said the wiring is sound. Strip IS getting voltage, and even the accelerometer was logging data from before, so I'm at an impasse...don't know what else I could test here beyond what I already have ...

![img_5317](https://cloud.githubusercontent.com/assets/308749/9554686/b14ffc60-4d95-11e5-9680-12b9fd8fd277.JPG)

**Comment by webdevbrian** [comment]
![img_5318](https://cloud.githubusercontent.com/assets/308749/9554706/d778955a-4d95-11e5-878c-b76920149b0e.JPG)

**Comment by NicoHood** [comment]
Maybe wrong end of the strip? Try it with 5V then.

**Comment by webdevbrian** [comment]
Yeah I flipped the other one I made already, to no avail ... I'm trying to figure out why he has it listed as 5V (check out the wiring diagram too, it says 5V), I'm running the same amount of LEDs (22) as he said he was in his final product ... I think there's something missing here...

**Comment by webdevbrian** [comment]
I've confirmed I have the *exact* strip as pictured in that wiring diagram

**Comment by NicoHood** [comment]
Try a 5V arduino. Or measure the voltage level, maybe it drops too much. Also USB cannot power that much leds, try a single one.

The error must be trivial. But please ask in the Fastled community since this is a github issue and not a support forum.

**Comment by webdevbrian** [comment]
Well, no actually -- this isn't a FastLED issue, so I'm not going to post there. The issue is with this project, we're just going back and forth about it thus making it look like 'support'. The issue still stands with Hermes in that, the wiring is perfect and it doesn't work.

I'm sure it is trivial, but not quite sure what else it could be.

**Comment by webdevbrian** [comment]
Alright so to wrap this up until the author comments:

1) I did do research, you can run LPD8806's on 3.7V
2) In the code he is using the Adafruit neopixel library for the LED strips, though he linked to LPD8806s which require a different library. I tried said library (the fast one he referenced in another place) no avail on either fronts. Flipped either side of the strip, still nothing. Broke out a 5V adapter, still nothing, flipped my clock and data pins, still nothing, checked wiring, everything is as it 'should' be via the supplied wiring diagram.
3) Flora does see accelerometers on both floras, they both return very similar data (which is good).
4) There is no description / readme going over the actual code. There are a few flags in the code which go unmentioned in the repo's readme such as: the keyboard input ... which is weird, but you change it from 0 to 1 to monitor the serial data. There is no elaboration if this code is ready to roll, i.e. you can put it on a flora and it should work.
5) The "parts" list should include adafruit's LiPo charger, which is required for charging the linked lipo 1,2000 mAh, 3.7v batteries
6) Elaboration, step by step of how one would set this up, which probably would be avoided if the above was included.

That's all I have so far -- both setups are currently still not working, with no real reason of why not. I've supplied pictures of my build, I can supply any more information as I'm sure someone else will have this issue if it's not this easy to reproduce the setup.

Hopefully @cloudwalking will respond, but thank you @NicoHood for the chit chat.

**Comment by webdevbrian** [comment]
For @cloudwalking - https://www.youtube.com/watch?v=DDS27doTOLE
